#!/usr/bin/env node
// Renders COMPLIANCE.md from jsii's canonical compliance suite and the report
// the RSpec run produces.
//
//   node scripts/compliance-report.js <path-to-jsii-checkout> [output.md]
//
// The suite is jsii's, not ours: `tools/jsii-compliance/suite.ts` in the jsii
// monorepo defines the canonical test names, and `ComplianceFormatter` tags our
// specs with them. Reading the suite from a checkout (rather than vendoring the
// list) means the report cannot silently drift from the standard it claims to
// measure — a test added upstream shows up here as unimplemented.
'use strict';

const fs = require('fs');
const path = require('path');
const Module = require('module');

const SUCCESS = '🟢'; // test succeeded
const FAILURE = '🔴'; // test is failing
const MISSING = '⭕'; // test is not implemented
const NOTAPPL = '⚪'; // test is not applicable to this language

/** Upstream compares names case-insensitively; do the same. */
function normalize(name) {
  return name.toUpperCase();
}

/** Markdown table cells cannot contain a raw pipe. */
function cell(text) {
  return String(text).replace(/\|/g, '\\|');
}

function glyph(result) {
  switch (result && result.status) {
    case 'success':
      return SUCCESS;
    case 'failure':
      return FAILURE;
    case 'n/a':
      return NOTAPPL;
    default:
      return MISSING;
  }
}

/**
 * @param {{ testCases: {name: string, description?: string}[],
 *           results: Record<string, {status: string, url?: string}>,
 *           suiteSource?: string }} input
 * @returns {string} the rendered document
 */
function renderComplianceReport({ testCases, results, suiteSource }) {
  let successes = 0;
  const rows = testCases.map((testCase, i) => {
    const result = results[normalize(testCase.name)];
    const status = glyph(result);
    if (status === SUCCESS) successes++;
    const marker = result && result.url ? `[${status}](${result.url})` : status;
    const test = testCase.description
      ? `${cell(testCase.name)} — ${cell(testCase.description)}`
      : cell(testCase.name);
    return `| ${i + 1} | ${test} | ${marker} |`;
  });

  const coverage = testCases.length
    ? ((successes / testCases.length) * 100).toFixed(2)
    : '0.00';

  return [
    '<!-- Generated by scripts/compliance-report.js — do not edit by hand. -->',
    '',
    '# Compliance',
    '',
    `The Ruby target implements **${successes} of ${testCases.length}** tests in`,
    `jsii's standard compliance suite (**${coverage}%**).`,
    '',
    'The suite is jsii\'s own (`tools/jsii-compliance/suite.ts`), the same one the',
    'other language bindings report against, and each spec here is tagged with its',
    'canonical test name. It is the bar for "is this binding compliant" — not the',
    'whole of what the target is tested for: the RSpec suite, the generator tests',
    'and the rosetta corpus all cover behaviour the standard suite does not reach.',
    '',
    `${SUCCESS} passing  ${FAILURE} failing  ${MISSING} not implemented  ${NOTAPPL} not applicable`,
    '',
    suiteSource ? `Suite read from ${suiteSource}.` : undefined,
    suiteSource ? '' : undefined,
    'Regenerate with `npm run compliance:report -- <path-to-jsii-checkout>` after',
    'running the compliance suite.',
    '',
    '| # | Test | Ruby |',
    '| --- | --- | --- |',
    ...rows,
    '',
  ]
    .filter((line) => line !== undefined)
    .join('\n');
}

/**
 * Load `suite.ts` from a jsii checkout without needing ts-node: transpile it and
 * evaluate it, stubbing the type-only `./schema` import.
 */
function loadSuite(jsiiCheckout) {
  const suitePath = path.join(jsiiCheckout, 'tools', 'jsii-compliance', 'suite.ts');
  const source = fs.readFileSync(suitePath, 'utf-8');
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const ts = require('typescript');
  const { outputText } = ts.transpileModule(source, {
    compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 },
  });

  const module_ = { exports: {} };
  const stubRequire = (request) =>
    request.startsWith('.') ? {} : Module.createRequire(suitePath)(request);
  // eslint-disable-next-line no-new-func
  new Function('exports', 'require', 'module', outputText)(
    module_.exports,
    stubRequire,
    module_,
  );
  return module_.exports.suite;
}

function main(argv) {
  const [checkout, output = 'COMPLIANCE.md'] = argv;
  if (!checkout) {
    console.error('usage: compliance-report.js <path-to-jsii-checkout> [output.md]');
    process.exit(2);
  }

  const reportPath = path.join(__dirname, '..', 'compliance', 'compliance-report.json');
  if (!fs.existsSync(reportPath)) {
    console.error(
      `no compliance report at ${reportPath} — run the compliance suite first ` +
        '(npm run test:compliance), which writes it.',
    );
    process.exit(1);
  }

  const suite = loadSuite(checkout);
  const raw = JSON.parse(fs.readFileSync(reportPath, 'utf-8'));
  const results = Object.fromEntries(
    Object.entries(raw).map(([name, value]) => [normalize(name), value]),
  );

  // A tag that matches nothing in the suite is a typo that would otherwise
  // inflate nothing and silently cover nothing — say so rather than ignore it.
  const known = new Set(suite.testCases.map((t) => normalize(t.name)));
  const unknown = Object.keys(results).filter((name) => !known.has(name));
  if (unknown.length > 0) {
    console.error(`tagged tests not present in the suite: ${unknown.join(', ')}`);
    process.exit(1);
  }

  const markdown = renderComplianceReport({
    testCases: suite.testCases,
    results,
    suiteSource: '`tools/jsii-compliance/suite.ts`',
  });
  fs.writeFileSync(output, markdown);
  console.log(`wrote ${output}`);
}

module.exports = { renderComplianceReport };

if (require.main === module) {
  main(process.argv.slice(2));
}
